version: 2
updates:
  # Update github actions:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
  # Update Rust dependencies:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
