version: '3.9'

services:
  daemon:
    image: enjin/daemon:latest
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./config.json:/opt/app/config.json
      - ./store:/opt/app/storage