services:
  daemon:
    image: enjin/wallet-daemon:latest
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
    env_file:
      - .env
    volumes:
      - ./config.json:/opt/app/config.json
      - ./store:/wallet/store