schema {
  mutation: Mutation
  query: Query
}

enum Network {
  CANARY
  ENJIN
}

enum Chain {
  MATRIX
  RELAY
}

enum TransactionStateEnum {
  PENDING
  BROADCAST
  EXECUTED
  FINALIZED
  FAILED
  ABANDONED
}

type Transaction {
  id: Int!
  transactionId: String
  state: TransactionStateEnum!
  transactionHash: String
  wallet: Wallet
  encodedData: String!
  network: String!
}

type Account {
  publicKey: String
  address: String
}

type Wallet {
  id: Int!
  account: Account
  externalId: String
  managed: Boolean!
  network: String!
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String!
  endCursor: String!
}

type TransactionEdge {
  node: Transaction!
  cursor: String!
}

type TransactionConnection {
  edges: [TransactionEdge]!
  pageInfo: PageInfo!
  totalCount: Int
}

type PendingTransaction {
  uuid: String!
  encodedData: String!
  wallet: ManagedWallet!
  shouldSignFuelTank: Boolean!
  fuelTankSignerExternalId: String
}

type PendingTransactionCursorPagination {
  data: [PendingTransaction!]!
  perPage: Int!
  previousCursor: String
  nextCursor: String
}

type ManagedWallet {
  publicKey: String
  externalId: String
}

type ManagedWalletCursorPagination {
  data: [ManagedWallet!]!
  perPage: Int!
  previousCursor: String
  nextCursor: String
}

input PopulateManagedWalletInput {
    externalId: String!
    publicKey: String!
    signedMessage: String!
}

input SignTransactionInput {
    uuid: String!
    signedExtrinsic: String!
    signedAbandonExtrinsic: String!
}

type Query {
  GetPendingTransactions(network: Network!, chain: Chain!, limit: Int = 25, cursor: String): PendingTransactionCursorPagination
  GetPendingManagedWalletCreations(network: Network!, chain: Chain!, limit: Int = 25, cursor: String): ManagedWalletCursorPagination
}

type Mutation {

  SignTransactions(
      transactions: [SignTransactionInput!]!
  ): Boolean!

  PopulateManagedWallets(
      wallets: [PopulateManagedWalletInput!]!
  ): Boolean!

  SetDaemonWalletAccount(
      publicKey: String!
      signedMessage: String!
  ): Boolean!
}
