schema {
  mutation: Mutation
  query: Query
}

enum Network {
  CANARY
  ENJIN
}

enum Chain {
  MATRIX
  RELAY
}

enum TransactionState {
  PENDING
  BROADCAST
  EXECUTED
  ABANDONED
  FINALIZED
}

type Transaction {
  id: Int!
  transactionId: String
  state: TransactionState!
  transactionHash: String
  wallet: Wallet
  encodedData: String!
  network: String!
}

type Account {
  publicKey: String
  address: String
}

type Wallet {
  id: Int!
  account: Account
  externalId: String
  managed: Boolean!
  network: String!
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String!
  endCursor: String!
}

type TransactionEdge {
  node: Transaction!
  cursor: String!
}

type TransactionConnection {
  edges: [TransactionEdge]!
  pageInfo: PageInfo!
  totalCount: Int
}

type GetPendingTransaction {
  wallet: WalletData
  uuid: String!
  encodedData: String!
}

type GetPendingTransactionsResult {
  data: [GetPendingTransaction!]!
  nextCursor: String
}

type WalletData {
  externalId: String
}

type GetPendingManagedWalletCreationsResult {
  data: [WalletData!]!
  nextCursor: String
}

input PopulateManagedWalletInput {
    externalId: String!
    publicKey: String!
    signedMessage: String!
}

type Query {
  GetPendingTransactions(network: Network!, chain: Chain!, limit: Int = 25, cursor: String): GetPendingTransactionsResult
  GetPendingManagedWalletCreations(network: Network!, chain: Chain!, limit: Int = 25, cursor: String): GetPendingManagedWalletCreationsResult
}

type Mutation {

  UpdateTransaction(
    id: Int!
    signingAccount: String
    state: TransactionState
    transactionHash: String
    signedAtBlock: Int
  ): Boolean!

  PopulateManagedWallets(
      wallets: [PopulateManagedWalletInput!]!
  ): Boolean!

  UpdateUser(
    account: String!
  ): Boolean!
}
