name: Build and Release
on:
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Set up homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install dependencies
        run: brew install messense/macos-cross-toolchains/x86_64-unknown-linux-gnu mingw-w64

      - name: Checkout repository
      - uses: actions/checkout@v4

      - name: Setup toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build binaries
        run: cargo build --release

      - name: Archive apple arm64
        uses: vimtor/action-zip@v1.2
        with:
          files: target/aarch64-apple-darwin/release/wallet-daemon
          dest: wallet-daemon_${{github.ref_name}}_arm64-apple-darwin.zip

      - name: Archive apple x86_64
        uses: vimtor/action-zip@v1.2
        with:
          files: target/x86_64-apple-darwin/release/wallet-daemon
          dest: wallet-daemon_${{github.ref_name}}_x86_64-apple-darwin.zip

      - name: Archive windows x86_64
        uses: vimtor/action-zip@v1.2
        with:
          files: target/x86_64-pc-windows-gnu/release/wallet-daemon
          dest: wallet-daemon_${{github.ref_name}}_x86_64-pc-windows-gnu.zip

      - name: Archive linux x86_64
        uses: vimtor/action-zip@v1.2
        with:
          files: target/x86_64-unknown-linux-gnu/release/wallet-daemon
          dest: wallet-daemon_${{github.ref_name}}_x86_64-unknown-linux-gnu.zip

      - name: Upload artifacts apple arm64
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: wallet-daemon_${{github.ref_name}}_arm64-apple-darwin.zip

      - name: Upload artifacts apple x86_64
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: wallet-daemon_${{github.ref_name}}_x86_64-apple-darwin.zip

      - name: Upload artifacts windows x86_64
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: wallet-daemon_${{github.ref_name}}_x86_64-pc-windows-gnu.zip

      - name: Upload artifacts linux x86_64
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: wallet-daemon_${{github.ref_name}}_x86_64-unknown-linux-gnu.zip
