name: Build and Release
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        toolchain: ["arm64-apple-darwin", "x86_64-apple-darwin", "x86_64-pc-windows-gnu", "x86_64-unknown-linux-gnu"]

    name: Build ${{ matrix.toolchain }}
    steps:
      - name: Set up homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install dependencies
        run: brew install messense/macos-cross-toolchains/x86_64-unknown-linux-gnu mingw-w64

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build binaries
        run: cargo build --release

      - name: Archive ${{ matrix.toolchain }}
        uses: vimtor/action-zip@v1.2
        with:
          files: target/${{ matrix.toolchain }}/release/wallet-daemon
          dest: wallet-daemon_${{github.ref_name}}_${{ matrix.toolchain }}.zip

      - name: Upload artifacts ${{ matrix.toolchain }}
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: wallet-daemon_${{github.ref_name}}_${{ matrix.toolchain }}.zip
