name: Clippy and Format
on:
  push:

jobs:
  clippy:
    name: Clippy
    runs-on: macos-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install dependencies
        run: brew install messense/macos-cross-toolchains/x86_64-unknown-linux-gnu mingw-w64 openssl

      - name: Configure OpenSSL for cross-compilation
        run: |
          export OPENSSL_DIR=$(brew --prefix openssl)
          export PKG_CONFIG_ALLOW_CROSS=1
          echo "OPENSSL_DIR=$OPENSSL_DIR" >> $GITHUB_ENV
          echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV

      - name: Checkou repository
        uses: actions/checkout@v4

      - name: Setup toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run clippy
        uses: auguwu/clippy-action@1.4.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
