name: PR Agent
on:
  pull_request:
  issue_comment:

jobs:
  pr_agent_job:
    name: Run agent
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write

    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@v0.26
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
