name: Security Audit
on:
  push:

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: read
      contents: read
      
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
