name: Test builds releases
on:
  pull_request:
  push:

jobs:
  build-linux:
    name: Build x86_64-unknown-linux-gnu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo build --release

  build-windows:
    name: Build x86_64-pc-windows-gnu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rust-build/rust-build.action@v1.4.5
        with:
          RUSTTARGET: "x86_64-pc-windows-gnu"
          UPLOAD_MODE: "none"
          TOOLCHAIN_VERSION: "1.82"
          SRC_DIR: src
          ARCHIVE_TYPES: "zip"

  build-mac:
    name: Build x86_64-apple-darwin
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.82"
          target: x86_64-apple-darwin
          default: true
          override: true
      - run: cargo build --release
