name: Test Builds Binaries
on:
  pull_request:
  push:

jobs:
  build:
    name: Test it builds binaries
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "1.83"
          target: "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-gnu"
      - run: cargo build --release
