name: Test Builds Binaries
on:
  pull_request:
  push:

jobs:
  build:
    name: Test it builds binaries
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo build --release
