name: Test Binary Build
on:
  push:

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
      - id: set-up-homebrew
      - uses: Homebrew/actions/setup-homebrew@master

      - name: Install dependencies
      - run: brew install messense/macos-cross-toolchains/x86_64-unknown-linux-gnu mingw-w64

      - uses: actions/checkout@v4

      - name: Build
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo build --release
